### ISSUE TITLE
core functions removed

### ISSUE THREAD

**Issue by akavkl** [lamminhthien-ntu/OneUI-3.1-Debloaat-for-Battery-Optimize#1]
Dolby EQ has been removed as well as system updater

**Comment by akavkl** [comment]
these 2 I noticed immediately 
could be more

**Comment by lamminhthien-ntu** [comment]
Sofware updater: app:Cập nhật phần mềm
package:com.wssyncmldm
Launcher:null



Dobly Atmos
app:SoundAlive
package:com.sec.android.app.soundalive
Launcher:null

Vào 14:35, CN, 10 Th10, 2021 Voske koristel ***@***.***> đã
viết:

**Comment by lamminhthien-ntu** [comment]
You using CTRL+F to find and
type command: pm install-existing "package_name" to reinstall them.
